version: '3.8'

services:
  ptk:
    build:
      context: .
      dockerfile: Dockerfile
    image: ptk:latest
    container_name: ptk_dev
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - ./:/ros2_ws/src/ptk
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
    command: /bin/bash
